#端口映射-hostPort
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demoapp
  namespace: dev
  labels:
    app: nginx
  annotations:
    author: xiaojie.bai
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      restartPolicy: Always
      containers:
      - name: demoapp
        image: ikubernetes/demoapp:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - name: nginx-port
          #宿主机的8080端口映射到容器的80端口，缺点pod被调度的主机事先未知
          containerPort: 80
          hostPort: 8080
          protocol: TCP
