#对proxy容器的80端口发起请求,是否可以将流量代理转发问到demoapp容器的8080端口
apiVersion: v1
kind: Pod
metadata:
  name: sidecar-container-demo
  namespace: dev
  labels:
    app: nginx
  annotations:
    author: xiaojie.bai
spec:
  restartPolicy: Always
  containers:
  - name: proxy
    image: envoyproxy/envoy-alpine:v1.13.1
    command:
    - /bin/sh
    - -c
    args:
    - echo 185.199.108.133 raw.githubusercontent.com >> /etc/hosts && sleep 3 && envoy  -c /etc/envoy/envoy.yaml
    lifecycle:
      postStart:
        exec:
          command:
          - /bin/sh
          - -c
          - wget -O /etc/envoy/envoy.yaml https://raw.githubusercontent.com/iKubernetes/Kubernetes_Advanced_Practical_2rd/master/chapter4/envoy.yaml
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    env:
    - name: HOST
      value: "127.0.0.1"
    - name: PORT
      value: "8080"
