
apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: httpproxy-health-check
  namespace: dev
spec:
  virtualhost:
    fqdn: testing0008.eniot.io
  routes:
  - conditions:
    - prefix: /
    healthCheckPolicy:
      path: /
      intervalSeconds: 5
      timeoutSeconds: 2
      unhealthyThresholdCount: 3
      healthyThresholdCount: 5
    services:
    - name: demo-2
      port: 80
    - name: demo
      port: 80
