#-m 1:内存压力测试的进程
#-c 1:cup压力测试的进程
apiVersion: v1
kind: Pod
metadata:
  name: stress-demo
  namespace: dev
  labels:
    app: nginx
  annotations:
    author: xiaojie.bai
spec:
  containers:
  - name: stress
    image: ikubernetes/stress-ng
    command: ["/usr/bin/stress-ng","-m 1","-c 1","--metrics-brief"]
    resources:
      requests:
        memory: "128Mi"
        cpu: "200m"
