apiVersion: v1
kind: Pod
metadata:
  name: downwardapi-volume-demo
  namespace: dev
  labels:
    zone: zone1
    rack: rack100
    app: demoapp
  annotations:
    region: ease-cn
spec:
  restartPolicy: Always
  containers:
  - name: demoapp
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    ports:
    - name: nginx-port
      containerPort: 80
    resources:
      requests:
        memory: "32Mi"
        cpu: "250m"
      limits:
        memory: "64Mi"
        cpu: "500m"
    volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
      readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        defaultMode: 420
        items:
        - fieldRef:
            fieldPath: metadata.namespace
          path: pod_namespace
        - fieldRef:
            fieldPath: metadata.labels
          path: pod_labels
        - fieldRef:
            fieldPath: metadata.annotations
          path: pod_annotations
        - resourceFieldRef:
            containerName: demoapp
            resource: limits.cpu
          path: "cpu_limit"
        - resourceFieldRef:
            containerName: demoapp
            resource: requests.memory
          path: "mem_request"
