#generic类型
kubectl create secret generic mysql-root-authn --from-literal=username=root --from-literal=password=iLinux -n dev

#用户名和密码用于basic认证
kubectl create secret generic web-basic-authn --from-literal=usename=ops --from-literal=password=iK8S  --type="kubernetes.io/basic-auth" -n dev

#ceph认证用户名可以明文提供，仅需要保存密钥信息
kubectl create secret  generic ceph-kube-secret --type=kubernetes.io/rbd -n dev

#基于ssh密钥认证
kubectl create secret generic ssh-key-secret --from-file=ssh-privatekey=$HOME/.ssh/id_rsa  --type=kubernetes.io/ssh-auth -n dev

# kubectl get secret -n dev
NAME                  TYPE                                  DATA   AGE
ceph-kube-secret      kubernetes.io/rbd                     0      10m
default-token-5sbkn   kubernetes.io/service-account-token   3      12d
mysql-root-authn      Opaque                                2      19m
ssh-key-secret        kubernetes.io/ssh-auth                1      6m54s
web-basic-authn       kubernetes.io/basic-auth              2      14m

#node-controller控制器
#kubectl get  secret $(kubectl get secrets -n kube-system |awk '/node-controller/ {print $1 }') -o yaml -n kube-system|grep type
type: kubernetes.io/service-account-token

#过程引导
#kubectl get  secret $(kubectl get secrets -n kube-system |awk '/^bootstrap/ {print $1 }') -o yaml -n kube-system|grep type     
type: kubernetes.io/service-account-token
