#secret配置清单
apiVersion: v1
kind: Secret
metadata:
  name: secret-demo
  namespace: dev
#stringData:  #明文
   #username: redis
   #password: redisp@ss
 data:          #base64编码密文
   username: cmVkaXMK
   password: cmVkaXNwQHNzCg==
type: Opaque

#generic类型
kubectl create secret generic mysql-root-authn --from-literal=username=root --from-literal=password=iLinux -n dev

#用户名和密码用于basic认证
kubectl create secret generic web-basic-authn --from-literal=usename=ops --from-literal=password=iK8S  --type="kubernetes.io/basic-auth" -n dev

#ceph认证用户名可以明文提供，仅需要保存密钥信息
kubectl create secret  generic ceph-kube-secret --type=kubernetes.io/rbd -n dev

#基于ssh密钥认证
kubectl create secret generic ssh-key-secret --from-file=ssh-privatekey=$HOME/.ssh/id_rsa  --type=kubernetes.io/ssh-auth -n dev

#node-controller控制器
#kubectl get  secret $(kubectl get secrets -n kube-system |awk '/node-controller/ {print $1 }') -o yaml -n kube-system|grep type
type: kubernetes.io/service-account-token

#过程引导
#kubectl get  secret $(kubectl get secrets -n kube-system |awk '/^bootstrap/ {print $1 }') -o yaml -n kube-system|grep type     
type: kubernetes.io/service-account-token

# tls类型
genrsa -out nginx.key 2048
openssl req -new -x509 -key nginx.key -out nginx.crt -subj /C=CN/ST=Beijing/O=Devops/CN=master
kubectl create secret tls nginx-ssl-secret --key=./nginx.key --cert=./nginx.crt -n dev
kubectl get secret -n dev|grep nginx
nginx-ssl-secret      kubernetes.io/tls

#docker-registry类型
kubectl create secret  docker-registry local-registry --docker-username=ops --docker-password=abcd --docker-email=ops@ilinux.io -n dev

#常见secret类型
#kubectl get secret -n dev
NAME                  TYPE                                  DATA   AGE
ceph-kube-secret      kubernetes.io/rbd                     0      44m
default-token-5sbkn   kubernetes.io/service-account-token   3      12d
local-registry        kubernetes.io/dockerconfigjson        1      17s
mysql-root-authn      Opaque                                2      53m
nginx-ssl-secret      kubernetes.io/tls                     2      6m20s
ssh-key-secret        kubernetes.io/ssh-auth                1      41m
web-basic-authn       kubernetes.io/basic-auth              2      48m


