#引用存储卷configmap资源中的部分键值数据
apiVersion: v1
kind: Pod
metadata:
  name: configmap-volume-demo
  namespace: dev
spec:
  containers:
  - name: nginx-server
    image: nginx:alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: ngxconf
      mountPath: /etc/nginx/conf.d/
      readOnly: true
  volumes:
  - name: ngxconf
    configMap:
      name: nginx-spec
      items:                #要暴露的键值数据
      - key: node.conf      #引用configmap资源中的键   
        path: node01.conf   # 对应的键在容器挂载目录中映射的文件名称
        mode: 644           #文件的权限
      - key: orc.conf
        path: orc1.conf
      optional: false

