apiVersion: v1
kind: ConfigMap
metadata:
  name: pod-envfrom-configmap
  namespace: dev
data:
  PORT: "8090"
  HOST: 0.0.0.0
---
apiVersion: v1
kind: Pod
metadata:
  name: podrefconfigmap
  namespace: dev
spec:
  containers:
  - name: configmap-pod-map
    image: ikubernetes/demoapp:v1.0
    imagePullPolicy: IfNotPresent
    envFrom:    #一次性引用多个configmap资源
    - prefix: "SPEC_"    #给引用的变量添加前缀
      configMapRef:
        name: pod-envfrom-configmap
        optional: false
