apiVersion: v1
kind: ConfigMap
metadata:
  name: alert-config
  namespace: kube-mon
data:
  config.yml: |-
    global:
      resolve_timeout: 5m
      smtp_smarthost: 'smtp.qq.com:465'
      smtp_from: '1533675521@qq.com'
      smtp_auth_username: '1533675521@qq.com'
      smtp_auth_password: 'jcgsowxsyftrgihj'
      smtp_require_tls: false

    route:
      group_by: ['alertname']
      group_wait: 5s
      repeat_interval: 5m
      receiver: 'email'

    receivers:
    - name: 'email'
      email_configs:
      - to: '1533675521@qq.com'
        send_resolved: true  
