apiVersion: v1
kind: Pod
metadata:
  name: vol-nfs-demo
  namespace: dev
  labels:
    app: redi
spec:
  containers:
  - name: redis
    image: redis:alpine
    ports:
    - name: redisport
      containerPort: 6379
    securityContext:
      runAsUser: 999
    volumeMounts:
    - name: redisdata
      mountPath: /data
  volumes:
    - name: redisdata
      nfs:
        server: 172.16.33.101
        path: /home/redis
        readOnly: false
