#实例-
apiVersion: v1
kind: Pod
metadata:
  name: volumes-emptydir-demo
  namespace: dev
spec:
  restartPolicy: Always
  initContainers:
  - name: config-file-downloader
    image: ikubernetes/admin-box
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    args:
    - echo 185.199.108.133 raw.githubusercontent.com >> /etc/hosts &&  wget -O /data/envoy.yaml https://raw.githubusercontent.com/iKubernetes/Kubernetes_Advanced_Practical_2rd/master/chapter4/envoy.yaml
    volumeMounts:
    - name: config-file-store
      mountPath: /data
  containers:
  - name: envoy
    image: envoyproxy/envoy-alpine:v1.13.1
    command:
    - /bin/sh
    - -c
    args:
    - envoy -c /etc/envoy/envoy.yaml
    volumeMounts:
    - name: config-file-store
      mountPath: /etc/envoy
  volumes:
  - name: config-file-store
    emptyDir:
      medium: Memory
      sizeLimit: 16Mi
#实例二
apiVersion: v1
kind: Pod
metadata:
  name: share-demo
  namespace: dev
spec:
  initContainers:
  - name: write
    image: busybox:latest
    imagePullPolicy: IfNotPresent
    command:
    - /bin/sh
    - -c
    args:
    - echo Share-data >> /empty/index.html
    volumeMounts:
    - name: html
      mountPath: /empty/
  containers:
  - name: read
    image: ikubernetes/myapp:v1
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: html
      mountPath: /usr/share/nginx/html/
  volumes:
  - name: html
    emptyDir: {}
